; keep in sync with pnlc.c, pnlc.vim, 'examples/pnlc definitional.pnlc',
; 'examples/pnlc metacircular.pnlc' and 'examples/pnlc shallow.pnlc'
<term> ::= "." <ws> <term> <term>            ; application
         | "\\" <ws> <var> <term>            ; abstraction
         | "#" <line> <ws> <term>            ; comment
         | <var> & (? head none of ".\\#" ?) ; variable
<line> ::= (? not '\n' ?)* "\n"
<var> ::= (? `!isspace` ?)+ (? `isspace` ?)+ ; assuming isspace(EOF)
<ws> ::= (? `isspace` ?)*
